<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net7.0</TargetFramework><EnableDynamicLoading>true</EnableDynamicLoading><TargetExt>.rhp</TargetExt><Version>1.0.1</Version><Title>Pachyderm Acoustic Simulation</Title><Company>Open Research in Acoustical Science and Education, Inc.</Company><Description>Repaired GH2 component library</Description><RootNamespace>PachydermGH2</RootNamespace><EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems><NuGetAudit>false</NuGetAudit><CheckEolTargetFramework>false</CheckEolTargetFramework></PropertyGroup>
 <PropertyGroup>
  <PlatformTarget>x64</PlatformTarget>
 </PropertyGroup>
 <ItemGroup><Compile Remove="tests/**/*.cs" /></ItemGroup>
 <ItemGroup>
  <EmbeddedResource Include="../../Resources/*.png;../../Resources/*.bmp">
   <Link>Resources/%(Filename)%(Extension)</Link>
   <LogicalName>PachydermGH2.Resources.%(Filename)%(Extension)</LogicalName>
  </EmbeddedResource>
  <EmbeddedResource Include="Icons/*.ghicon"/>
  <EmbeddedResource Include="Icons/*.ico"/>
 </ItemGroup>
 <ItemGroup>
<Reference Include="Grasshopper2"><HintPath>lib/Grasshopper2.dll</HintPath><Private>false</Private></Reference>
<Reference Include="GrasshopperIO"><HintPath>lib/GrasshopperIO.dll</HintPath><Private>false</Private></Reference>
<Reference Include="RhinoCommon"><HintPath>lib/RhinoCommon.dll</HintPath><Private>false</Private></Reference>
<Reference Include="Rhino.UI"><HintPath>lib/Rhino.UI.dll</HintPath><Private>false</Private></Reference>
<Reference Include="Eto"><HintPath>lib/Eto.dll</HintPath><Private>false</Private></Reference>
<Reference Include="Hare"><HintPath>lib/Hare.dll</HintPath><Private>false</Private></Reference>
<Reference Include="Pachyderm_Acoustic_Universal"><HintPath>lib/Pachyderm_Acoustic_Universal.dll</HintPath><Private>false</Private></Reference>
<Reference Include="CLF_Read"><HintPath>lib/CLF_Read.dll</HintPath><Private>false</Private></Reference>
<Reference Include="MathNet.Numerics"><HintPath>lib/MathNet.Numerics.dll</HintPath><Private>false</Private></Reference>
<Reference Include="MathNet.Numerics.FSharp"><HintPath>lib/MathNet.Numerics.FSharp.dll</HintPath><Private>false</Private></Reference>
<Reference Include="MathNet.Symbolics"><HintPath>lib/MathNet.Symbolics.dll</HintPath><Private>false</Private></Reference>
<Reference Include="FSharp.Core"><HintPath>lib/FSharp.Core.dll</HintPath><Private>false</Private></Reference>
<Reference Include="ScottPlot"><HintPath>lib/ScottPlot.dll</HintPath><Private>false</Private></Reference>
<Reference Include="ScottPlot.Eto"><HintPath>lib/ScottPlot.Eto.dll</HintPath><Private>false</Private></Reference>
<Reference Include="System.Drawing.Common"><HintPath>lib/System.Drawing.Common.dll</HintPath><Private>false</Private></Reference>
<Reference Include="System.Windows.Extensions"><HintPath>lib/System.Windows.Extensions.dll</HintPath><Private>false</Private></Reference>
<Reference Include="Pachyderm_Acoustic"><HintPath>lib/Pachyderm_Acoustic.rhp</HintPath><Private>false</Private></Reference></ItemGroup>
</Project>
